version: 2
updates:
  #  - package-ecosystem: composer
  #    directory: "/"
  #    schedule:
  #      interval: monthly
  #    open-pull-requests-limit: 10
  #    labels:
  #      - "dependencies"
  #      - "composer"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Too noisy. See https://github.community/t/increase-if-necessary-for-github-actions-in-dependabot/179581
    open-pull-requests-limit: 0
#    labels:
#      - "dependencies"
